// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KafkaReduceMessageSize.Core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class OrderAvroModel : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""OrderAvroModel"",""namespace"":""KafkaReduceMessageSize.Core"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Status"",""type"":""int""},{""name"":""CreationTime"",""type"":""long""},{""name"":""ProductId"",""type"":""int""},{""name"":""CustomerId"",""type"":""int""}]}");
		private string _Id;
		private int _Status;
		private long _CreationTime;
		private int _ProductId;
		private int _CustomerId;
		public virtual Schema Schema
		{
			get
			{
				return OrderAvroModel._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				this._Status = value;
			}
		}
		public long CreationTime
		{
			get
			{
				return this._CreationTime;
			}
			set
			{
				this._CreationTime = value;
			}
		}
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		public int CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				this._CustomerId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Status;
			case 2: return this.CreationTime;
			case 3: return this.ProductId;
			case 4: return this.CustomerId;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Status = (System.Int32)fieldValue; break;
			case 2: this.CreationTime = (System.Int64)fieldValue; break;
			case 3: this.ProductId = (System.Int32)fieldValue; break;
			case 4: this.CustomerId = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
